source 'https://rubygems.org'
ruby '2.1.3'
gem 'annotate'
gem 'autoprefixer-rails'
gem 'backbone-on-rails'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'bootstrap-switch-rails', '~> 3.3.1'
gem 'bootstrap-tagsinput-rails'
gem 'bootstrap-select-rails'
gem 'cancancan', '~> 1.9'
gem 'coffee-rails', '~> 4.0.0'
gem 'delayed_job_active_record'
gem 'devise'
gem 'dotenv-rails'
gem 'elasticsearch-model'
gem 'elasticsearch-rails'
gem 'faker'
gem 'gon'
gem 'high_voltage'
gem 'isbn', '~> 2.0.10'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'mysql2'
gem 'nokogiri'
gem 'rails', '4.1.5'
gem 'react-rails', '~> 1.0.0', github: 'reactjs/react-rails'
gem 'sass-rails', '~> 4.0.3'
gem 'sdoc', '~> 0.4.0',            group: :doc
gem 'slim'
gem 'sucker_punch', '~> 1.0'
gem 'toastr-rails'
gem 'turbolinks'
gem 'underscore-rails'
gem 'uglifier', '>= 1.3.0'
gem 'will_paginate'
gem 'whenever', require: false
group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'foreman'
  gem 'guard-rubocop'
  gem 'guard-livereload'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'rubocop'
  gem 'spring'
end
group :development, :test do
  gem 'thin'
  gem 'sqlite3'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'guard-rspec'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'railroady'
  gem 'rspec-rails'
  gem 'launchy'
  gem 'browserify-rails', '~>0.5'
end
group :production do
  gem 'bonsai-elasticsearch-rails'
  gem 'execjs'
  gem 'rails_12factor'
  gem 'therubyracer'
  gem 'unicorn'
end
