source 'https://rubygems.org'
ruby '2.1.3'
gem 'annotate'
gem 'autoprefixer-rails'
gem 'backbone-on-rails'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'bootstrap-tagsinput-rails'
gem 'cancancan', '~> 1.9'
gem 'coffee-rails', '~> 4.0.0'
gem 'delayed_job_active_record'
gem 'devise'
gem 'elasticsearch-model'
gem 'elasticsearch-rails'
gem 'faker'
gem 'gon'
gem 'high_voltage'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'nokogiri'
gem 'rails', '4.1.5'
gem 'react-rails', '~> 1.0.0.pre', github: 'reactjs/react-rails'
gem 'sass-rails', '~> 4.0.3'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'slim'
gem 'toastr-rails'
gem 'turbolinks'
gem 'underscore-rails'
gem 'uglifier', '>= 1.3.0'
gem 'isbn', '~> 2.0.10'
gem 'will_paginate'
gem 'whenever', :require => false
group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'foreman'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'spring'
end
group :development, :test do
  gem 'thin'
  gem 'sqlite3'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'railroady'
  gem 'rspec-rails'
  gem 'launchy'
end
group :production do
  gem 'rails_12factor'
  gem 'pg'
  gem 'unicorn'
  gem 'bonsai-elasticsearch-rails'
end
