source 'https://rubygems.org'
ruby '2.1.3'
gem 'bourbon'
gem 'cancancan', '~> 1.9'
gem 'coffee-rails', '~> 4.0.0'
gem 'devise'
gem 'haml-rails'
gem 'high_voltage'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'neat'
gem 'rails', '4.1.5'
gem 'sass-rails', '~> 4.0.3'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'sqlite3'
gem 'thin'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'html2haml'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'spring'
end
group :development, :test do
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'rspec-rails'
end
